oss-review-toolkit/ort-workbench

src/main/kotlin/state/ViolationsState.kt
src/main/kotlin/util/SpdxExpressionStringComparator.kt

Add a string comparator for `SpdxExpression` to fix sorting license
expressions.

ViolationsState: Fix sorting license expressions

---

build.gradle.kts
gradle.properties
settings.gradle.kts
src/main/kotlin/ui/Menu.kt

Gradle: Use ORT core's way to centrally declare dependency versions

---

build.gradle.kts
src/main/kotlin/App.kt
src/main/kotlin/ui/Content.kt

Fixes the issue that text was not readable on multiple UI components when using MacOS's dark system setting.
Before:
After:

Fix dark mode colors

---

src/main/kotlin/model/OrtModel.kt

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

OrtModel: Ensure the `ORT_WORKBENCH_CONFIG_DIRNAME` exists

---

build.gradle.kts

This avoids the
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
error and allows messages logged by libraries that use the SLF4J API to
be forwarded to the Log4j implementation.
Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

Gradle: Add the SLF4J implementation for Log4j

---

src/main/kotlin/model/OrtModel.kt

Even if a `(Postgres)FileArchiverStorage` could not be created at the
time a file is loaded (e.g. because a PostgreSQL database server cannot
be reached), continue loading the result file in order to display it.
As a fallback, create a `FileArchiverFileStorage` in that case.
Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

OrtModel: Continue loading a file on error `FileArchiverStorage`

---

src/main/kotlin/model/OrtModel.kt

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

OrtModel: Log when falling back to the default scanner file archiver

---

gradle/libs.versions.toml
src/main/kotlin/ui/summary/Summary.kt

This allows to upgrade to Kotlin 1.7.10 in order to align with ORT's
Kotlin version. Also see [1].
[1]: https://github.com/JetBrains/compose-jb/releases

Gradle: Start using Compose-1.2-based desktop-alpha-releases

---

src/main/kotlin/ui/App.kt
src/main/kotlin/ui/AppState.kt

Fix the issue that the file dialog sometimes immediately re-opens if a file is selected with a double click. See the commit messages for details.

Fix FileDialog double click issue

---

build.gradle.kts
gradle/libs.versions.toml

Dependency updates

---

src/main/kotlin/model/OrtModel.kt

When reloading the same file the `_ortResult` `StateFlow` was assigned the same value as before and as a result no new value got emitted. This resulted in the UI getting stuck because the state was never updated from `LOADING_RESULT`.
Fix this by resetting `_ortResult` to `null` before assigning any new value.
Fixes #49.

OrtModel: Fix reloading the same file

---

renovate.json

The "pin" range strategy actually means to "convert ranges to exact versions", see [1].
[1]: https://docs.renovatebot.com/configuration-options/#rangestrategy

Renovate: Use the correct syntax to pin / ignore dependencies

---

build.gradle.kts
gradle/libs.versions.toml
renovate.json
src/main/kotlin/model/OrtApi.kt
src/main/kotlin/model/OrtModel.kt
src/main/kotlin/ui/summary/SummaryViewModel.kt

This allows to get rid of sticking SnakeYAML to version 1.31. For the
complete list of commits see [1].
[1]: https://github.com/oss-review-toolkit/ort/compare/0f28f92094...7aa61bf96b

Upgrade to a version of ORT that configures Jackson for big YAML files

---

renovate.json

See [1]. This is a fixup for c8ccdb3.
[1]: https://docs.renovatebot.com/key-concepts/dashboard/#how-to-disable-the-dashboard

Fix disabling the Renovate dependency dashboard

---

build.gradle.kts

This silences false-positive error messages in IntellJ [1] [2].
[1]: https://youtrack.jetbrains.com/issue/KTIJ-19369
[2]: https://github.com/gradle/gradle/issues/22797

Gradle: Suppress DSL_SCOPE_VIOLATION

---

detekt.yml
src/main/kotlin/model/FilterData.kt
src/main/kotlin/ui/issues/Issues.kt
src/main/kotlin/ui/issues/IssuesState.kt
src/main/kotlin/ui/issues/IssuesViewModel.kt
src/main/kotlin/ui/packages/Packages.kt
src/main/kotlin/ui/packages/PackagesState.kt
src/main/kotlin/ui/packages/PackagesViewModel.kt
src/main/kotlin/ui/violations/Violations.kt
src/main/kotlin/ui/violations/ViolationsState.kt
src/main/kotlin/ui/violations/ViolationsViewModel.kt
src/main/kotlin/ui/vulnerabilities/Vulnerabilities.kt
src/main/kotlin/ui/vulnerabilities/VulnerabilitiesState.kt
src/main/kotlin/ui/vulnerabilities/VulnerabilitiesViewModel.kt
src/main/kotlin/util/FilterButton.kt
src/main/kotlin/util/FilterMatchers.kt
src/main/kotlin/util/ResolutionStatus.kt

Align the layout of the `Issues`, `Packages`, `Violations`, and `Vulnerabilities` screens and refactor the filter logic. The refactoring is mainly a preparation for moving the filters to a side panel and sharing more code between the screens which will happen in a follow-up PR. Until then, the layout can break if the window is not wide enough to show all filters. See the commit messages for details.

Refactor list screens

---

.commitlintrc.yml
.github/workflows/static-analysis.yml
renovate.json

See [1]. This is a preparation for release automation including release notes. At the same time, configure Renovate to use "deps" as the type and no scope at all, see [2].
[1]: https://www.conventionalcommits.org/
[2]: https://docs.renovatebot.com/semantic-commits/

ci(github): Start enforcing of Conventional Commits

---

src/main/kotlin/composables/tree/Tree.kt
src/main/kotlin/composables/tree/TreeState.kt
src/main/kotlin/ui/dependencies/Dependencies.kt
src/main/kotlin/ui/dependencies/DependenciesState.kt
src/main/kotlin/ui/dependencies/DependenciesViewModel.kt
src/main/kotlin/utils/MaterialIcon.kt
src/main/resources/material/chevron_right.svg

Extract the tree logic from the dependencies screen into a separate composable to make it reusable.

refactor: Extract tree composable

---

renovate.json

Enfore semantic commits [1] because Renovate does not auto-detect them.
[1]: https://docs.renovatebot.com/semantic-commits/#manually-enabling-or-disabling-semantic-commits

ci(renovate): Enforce semantic commits

---

build.gradle.kts

This is not needed for Kotlin 1.8 compatibility anymore as of 804306c.

build(Gradle): Stop using a Compose compiler development version

---

src/main/kotlin/ui/dependencies/DependenciesViewModel.kt

Fix showing transitive dependencies in the dependency tree view.
This is a fixup for 6e4eeb6.

fix(Dependencies): Fix showing transitive dependencies

---

src/main/kotlin/composables/FilterTextField.kt

If the text of a `TextField` is updated from a flow, this can lead to a jumping cursor and swallowed characters [1]. For a discussion of the issue see [2].
Fix this by introducing a local mutable state for the text value.
Fixes #109.
[1]: https://github.com/JetBrains/compose-multiplatform/issues/3089
[2]: https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5

fix(FilterTextField): Fix synchronization issues

---

build.gradle.kts

IntelliJ creates classpath.index files for the kotlin sources and the resources which can result in this error:
Entry classpath.index is a duplicate but no duplicate handling
strategy has been set.
Solve that by setting an appropriate duplicate handling strategy to exclude all but the first file. Also see [1].
[1]: https://youtrack.jetbrains.com/issue/IDEA-305759

Gradle: Set a duplicate handling strategy (to handle "classpath.index")

---

src/main/kotlin/ui/App.kt

Fix the issue again that the file dialog could reopen when selecting the file with a double-click. This was originally fixed in f4c4160 by checking if another file is already loading before showing the dialog. The check was removed in 47d7455 and it also did not make sense anymore to do this check in `openResultDialog` because since 871c2c2 there can be more than one instance of `OrtModel`. Therefore reintroduce the check in the `loadResult` function which opens the file dialog.

fix: Prevent file dialog from reopening

---

build.gradle.kts
gradle/libs.versions.toml
src/main/kotlin/lifecycle/MoleculeViewModel.kt

The Molecule Gradle plugin cannot be applied to the same project as the JetBrains Compose Gradle plugin. Both plugins attempt to configure the Compose compiler plugin which is incompatible. So just add the molecule runtime dependency.

deps: Update molecule to version 1.1.0

---

build.gradle.kts
gradle/libs.versions.toml
src/main/kotlin/composables/Tooltip.kt
src/main/kotlin/model/OrtModel.kt
src/main/kotlin/ui/App.kt
src/main/kotlin/ui/Menu.kt

Add an option to only use the resolved config from the ORT result file. Please see the commit messages for details.

Use only resolved config

---

gradle/libs.versions.toml

See [1]. This is supported by Compose 1.5.1 now.
[1]: https://github.com/JetBrains/kotlin/releases/tag/v1.9.10

deps: Upgrade Kotlin to version 1.9.10

---

build.gradle.kts

This is not required anymore as SW360 get published to Maven Central now. Also see [1] which part of ORT 2.0.0.
[1]: https://github.com/oss-review-toolkit/ort/commit/bc3404ca95cd44b3db9640e9b9a638bf55e3d649

chore(Gradle): Remove the SW360 repository declaration

---

gradle/libs.versions.toml

See [1].
[1]: https://blog.jetbrains.com/kotlin/2023/11/kotlin-1-9-20-released/

deps(Gradle): Upgrade Kotlin to version 1.9.20

---

build.gradle.kts
gradle/libs.versions.toml

With dependencies being updated on GitHub via Renovate now, there is little reason to keep this plugin to do the same locally. Keep the plain `versions` plugin for now, however, as just checking for new versions locally might be useful.

build(Gradle): Remove the `versionCatalogUpdate` plugin

---

build.gradle.kts
gradle/libs.versions.toml

Also see [1].
[1]: https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compiler.html#migrating-a-compose-multiplatform-project

deps(Gradle): Upgrade to Kotlin 2.0.0

---

build.gradle.kts
gradle/libs.versions.toml
src/main/kotlin/composables/FileDialog.kt

The fixes the file dialog to actually work on Linux with Wayland. Also see a similar discussion at [1].
For now, only the load dialog is implemented, as saving would require another callback anyway.
[1]: https://github.com/gradle/gradle-client/issues/10

refactor: Use FileKit for the `FileDialog`

---

gradle.properties
gradle/gradle-daemon-jvm.properties

The build uses ORT's Detekt rules which have been compiled with Java 21 as of ORT version 35.0.0, so also the Gradle build needs to be run with Java 21. Configure the Gradle daemon accordingly.

build(gradle): Also run the Gradle build with Java 21

---

build.gradle.kts

Always rely on the latest default.

build(gradle): Do not explicitly set a (lower) Kotlin API

---

settings.gradle.kts

Allow to build the project on machines where no matching local toolchain is found by bootstrapping one from remote.

build(gradle): Configure a toolchain provider for bootstrapping
