oss-review-toolkit/ort-workbench

- src/main/kotlin/App.kt
Fix the issue that the file dialog sometimes reopens after selecting a file, see the commit messages for details.
> Fix file dialog

- src/main/kotlin/ui/Dependencies.kt
Implement the project details card.
> Dependencies: Add project details

- README.md
- build.gradle.kts
- gradle.properties
> Miscellaneous small Gradle / detekt improvements

- gradle.properties
Unfortunately, there is no changelog [1] entry yet.
[1]: https://github.com/JetBrains/compose-jb/blob/master/CHANGELOG.md
> Gradle Upgrade Compose to version 1.1.0

- .github/CODEOWNERS
- .mailmap
> Add initial `CODEOWNERS` / `.mailmap` files

- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Dependency upgrades

- gradle.properties
> Dependency updates

- src/main/kotlin/ui/packages/PackagesViewModel.kt
> PackagesViewModel: Fix indentation

- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- settings.gradle.kts
> Migrate dependency declarations to a version catalog

- .gitattributes
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
> Gradle update

- gradle/libs.versions.toml
- src/main/kotlin/ui/dependencies/Dependencies.kt
- src/main/kotlin/ui/packages/Packages.kt
- src/main/kotlin/ui/packages/PackagesViewModel.kt
> Upgrade ORT

- .github/workflows/build.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/static-analysis.yml
> Miscellaneous small fixes and updates

- renovate.json
Closes #57. The individual update PRs should be enough.
> Disable the Renovate dependency dashboard issue

- src/main/kotlin/ui/dependencies/Dependencies.kt
> Align to not use underscores in package details titles

- src/main/kotlin/model/OrtModel.kt
- src/main/kotlin/theme/Color.kt
- src/main/kotlin/theme/Theme.kt
- src/main/kotlin/ui/App.kt
- src/main/kotlin/ui/Menu.kt
- src/main/kotlin/ui/TopBar.kt
- src/main/kotlin/ui/dependencies/Dependencies.kt
- src/main/kotlin/ui/dependencies/DependenciesState.kt
- src/main/kotlin/ui/dependencies/DependenciesViewModel.kt
- src/main/kotlin/ui/issues/Issues.kt
- src/main/kotlin/ui/packages/Packages.kt
- src/main/kotlin/ui/settings/Settings.kt
- src/main/kotlin/ui/settings/SettingsTab.kt
- src/main/kotlin/ui/settings/SettingsViewModel.kt
- src/main/kotlin/ui/violations/Violations.kt
- src/main/kotlin/ui/vulnerabilities/Vulnerabilities.kt
- src/main/kotlin/util/FilterButton.kt
- src/main/kotlin/util/FilterTextField.kt
- src/main/kotlin/util/Preview.kt
Prepare the app layout for upcoming features, make the design a bit more material-like, and add an option to select the theme.
Please note that this PR temporarily breaks the dark theme. This will be fixed in a follow-up PR.
> Start design improvements and minor improvements

- README.md
> README: Replace the individual Copyright with a generic one

- src/main/kotlin/navigation/Navigation.kt
- src/main/kotlin/navigation/NavigationController.kt
- src/main/kotlin/navigation/Screen.kt
- src/main/kotlin/ui/App.kt
- src/main/kotlin/ui/AppState.kt
- src/main/kotlin/ui/Menu.kt
- src/main/kotlin/ui/summary/Summary.kt
Add a navigation controller as preparation for supporting navigation with stacks and parameters.
> Add a basic NavigationController

- gradle/libs.versions.toml
See [1] for a list of changes.
[1]:  https://github.com/oss-review-toolkit/ort/compare/13f5dd2759...af0a83a2f8
>  deps: Upgrade ORT to the current main revision

- src/main/kotlin/composables/ScreenAppBar.kt
- src/main/kotlin/navigation/Navigation.kt
- src/main/kotlin/theme/Theme.kt
- src/main/kotlin/ui/App.kt
- src/main/kotlin/ui/packagedetails/PackageDetails.kt
- src/main/kotlin/ui/packagedetails/PackageDetailsState.kt
- src/main/kotlin/ui/packages/Packages.kt
- src/main/kotlin/utils/MaterialIcon.kt
- src/main/resources/material/arrow_back.svg
Add a package details view, see the commit messages for details.
> Package details

- src/main/kotlin/model/OrtApi.kt
- src/main/kotlin/ui/dependencies/DependenciesViewModel.kt
- src/main/kotlin/ui/issues/IssuesViewModel.kt
- src/main/kotlin/ui/packagedetails/PackageDetailsState.kt
- src/main/kotlin/ui/packages/PackagesViewModel.kt
- src/main/kotlin/ui/summary/SummaryViewModel.kt
See the commit messages for details.
> Make `OrtApi` properties private

- src/main/kotlin/ui/MainScreen.kt
Make the screen classes data classes so that existing screens can be found in the backstack by the generated equals function.
> fix(navigation): Make screens data classes

- src/main/kotlin/ui/issues/Issues.kt
- src/main/kotlin/ui/issues/IssuesState.kt
- src/main/kotlin/ui/issues/IssuesViewModel.kt
- src/main/kotlin/ui/packages/Packages.kt
- src/main/kotlin/ui/packages/PackagesState.kt
- src/main/kotlin/ui/packages/PackagesViewModel.kt
- src/main/kotlin/ui/violations/Violations.kt
- src/main/kotlin/ui/violations/ViolationsState.kt
- src/main/kotlin/ui/violations/ViolationsViewModel.kt
- src/main/kotlin/ui/vulnerabilities/Vulnerabilities.kt
- src/main/kotlin/ui/vulnerabilities/VulnerabilitiesState.kt
- src/main/kotlin/ui/vulnerabilities/VulnerabilitiesViewModel.kt
> refactor: Inline filter data with filter classes

- src/main/kotlin/composables/CircularProgressBox.kt
- src/main/kotlin/model/OrtModel.kt
- src/main/kotlin/navigation/NavController.kt
- src/main/kotlin/ui/dependencies/Dependencies.kt
- src/main/kotlin/ui/dependencies/DependenciesState.kt
- src/main/kotlin/ui/dependencies/DependenciesViewModel.kt
- src/main/kotlin/ui/issues/Issues.kt
- src/main/kotlin/ui/issues/IssuesState.kt
- src/main/kotlin/ui/issues/IssuesViewModel.kt
- src/main/kotlin/ui/packages/Packages.kt
- src/main/kotlin/ui/packages/PackagesState.kt
- src/main/kotlin/ui/packages/PackagesViewModel.kt
- src/main/kotlin/ui/summary/Summary.kt
- src/main/kotlin/ui/summary/SummaryState.kt
- src/main/kotlin/ui/summary/SummaryViewModel.kt
- src/main/kotlin/ui/violations/Violations.kt
- src/main/kotlin/ui/violations/ViolationsState.kt
- src/main/kotlin/ui/violations/ViolationsViewModel.kt
- src/main/kotlin/ui/vulnerabilities/Vulnerabilities.kt
- src/main/kotlin/ui/vulnerabilities/VulnerabilitiesState.kt
- src/main/kotlin/ui/vulnerabilities/VulnerabilitiesViewModel.kt
> Move expensive calculations out of UI thread

- src/main/kotlin/ui/App.kt
- src/main/kotlin/ui/WorkbenchController.kt
> Add support for external drag & drop to the initial screen

- .github/workflows/static-analysis.yml
- .reuse/dep5
- LICENSES/Apache-2.0.txt
- README.md
> Reuse compliance

- src/main/kotlin/composables/Extensions.kt
- src/main/kotlin/composables/Link.kt
- src/main/kotlin/ui/dependencies/Dependencies.kt
- src/main/kotlin/ui/packagedetails/PackageDetails.kt
> Add links to package details screen

- gradle/libs.versions.toml
See [1] for a list of changes.
[1]: https://github.com/oss-review-toolkit/ort/compare/caccff5a87...d86c176dc3
> deps: Upgrade ORT to the current main revision

- build.gradle.kts
- gradle/libs.versions.toml
- src/main/kotlin/model/OrtModel.kt
> Update ORT (and Kotlin)

- build.gradle.kts
- gradle/libs.versions.toml
See [1] for the list of changes.
[1]: https://github.com/oss-review-toolkit/ort/compare/023c7b06de...1.0.1
> build: Switch to official ORT release 1.0.1

- src/main/kotlin/composables/tree/Tree.kt
- src/main/kotlin/composables/tree/TreeState.kt
- src/main/kotlin/model/FilterData.kt
- src/main/kotlin/ui/dependencies/Dependencies.kt
- src/main/kotlin/ui/dependencies/DependenciesViewModel.kt
- src/main/kotlin/ui/issues/IssuesViewModel.kt
- src/main/kotlin/ui/packages/PackagesViewModel.kt
- src/main/kotlin/ui/violations/ViolationsViewModel.kt
- src/main/kotlin/ui/vulnerabilities/VulnerabilitiesViewModel.kt
> Preserve filters on model changes

- src/main/kotlin/ui/dependencies/DependenciesState.kt
- src/main/kotlin/ui/issues/IssuesState.kt
- src/main/kotlin/ui/summary/SummaryState.kt
- src/main/kotlin/ui/violations/ViolationsState.kt
- src/main/kotlin/ui/vulnerabilities/VulnerabilitiesState.kt
This improves symmetry with accompanying data classes in the same hierarchy, see [1].
[1]: https://kotlinlang.org/docs/whatsnew19.html#stable-data-objects-for-symmetry-with-data-classes
> chore: Use data objects in sealed hierarchies

- src/main/kotlin/ui/dependencies/Dependencies.kt
> Improvements to displaying project dependencies

- gradlew.bat
> build: Upgrade Gradle wrapper scripts

- build.gradle.kts
- gradle.properties
- src/main/kotlin/composables/tree/Tree.kt
- src/main/kotlin/ui/App.kt
- src/main/kotlin/ui/Menu.kt
- src/main/kotlin/ui/dependencies/Dependencies.kt
> Some minor Gradle-related improvements

- .reuse/dep5
- NOTICE
- README.md
Aligning ORT Workbench project with how we do things in the main ORT project.
> Fix copyrights in README and add NOTICE file

- .github/workflows/build.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/static-analysis.yml
- build.gradle.kts
- gradle.properties
> Build with Java 21

- src/main/kotlin/model/OrtApi.kt
- src/main/kotlin/ui/dependencies/Dependencies.kt
- src/main/kotlin/ui/dependencies/DependenciesState.kt
- src/main/kotlin/ui/dependencies/DependenciesViewModel.kt
> Fix the view of package curations

- renovate.json
Extend from config:recommended, add a "dependencies" label, pin GitHub actions, and shorten commit message titles for Gradle dependencies.
> ci(renovate): Align config with ORT

- build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
> Remove version plugin
